Ruby Enumerable Methods
frankopkusianwar/enumerable_methods pull request #1
Opened 2020-04-22 15:33 UTC by frankopkusianwar

#### What does this PR do?

- Adds Ruby enumerable methods to the enumerable module

### Description of Task to be completed?

 - Added the enumerable_custom.rb file.
 - Created the enumerable class and added the enumerable methods 
 - Ran validations on Rubocop.

#### How should this be manually tested?

- Clone this branch.
- open the enumerables_custom.rb on your code editor.
- open the terminal and run  *ruby enumerable_custom.rb* command

#### Screenshot

![screenshot](https://user-images.githubusercontent.com/40593659/80001799-784ea600-84c7-11ea-870b-db27a4794db6.PNG)

2020-04-22 17:10 UTC, stratospherique requested changes
### Great start @frankopkusianwar :clap: :clap: However, some methods need further refactoring in order to get approval for this project. Check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your methods :gear: 

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-04-22 17:10 UTC, stratospherique commented on enumerable_custom.rb
> +  end
* [x] should have working `my_select` identical and returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [x] my_select returns an enumerator if no block is given
  ```
    array = [1,2,5,8,7,98,4]
    p array.my_select.class # not Enumerator
  ```

2020-04-22 17:10 UTC, stratospherique commented on enumerable_custom.rb
> +  end
The issues with **my_none?**, **my_any?** and **my_all?** are similar. the methods should be able to: 

* [ ] Return a suitable boolean result if no arguments were passed.
  ```ruby
	array = [false, true, false, nil, []]
	puts array.my_any? # should print true
	puts array.my_all? # should print false
	puts array.my_none? # should print false
  ```
* [ ] Accept primitives, classes (i.e Integer, String, etc...) and Regex Expressions as arguments.
  ```ruby
	words = %w[dog door rod blade]
	puts words.my_all?(/c/) == words.all?(/c/) # false
	puts words.my_any?(/c/) == words.all?(/c/) # false
	puts words.my_none?(/c/) == words.all?(/c/) # true
  ```

2020-04-22 17:10 UTC, stratospherique commented on enumerable_custom.rb
> +  end
* [ ] should have working `my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_map returns a new array with the results of running block once for every element in enum.
  ```ruby
    array = [1,2,5,4,7]
    block = proc { |num| num < 5 }
    p array.my_map?(&block) == array.map?(&block) # false
  ```

2020-04-22 17:10 UTC, stratospherique commented on enumerable_custom.rb
> +  end
* [ ] should have working `my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
  ```ruby
    array = [4,7,8,89,9,6,5,12,4,2,5]
    operation = proc { |sum, n| sum + n  }
    p array.my_inject(&operation) == array.inject(&operation) # false
  ```

* [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(2, :*) # returns this error
    # ArgumentError:
        wrong number of arguments (given 2, expected 0..1)
      # ./enumerable_custom.rb:99:in `my_inject'
  ```

2020-04-23 19:26 UTC, shshamim63 requested changes
## Status :1234: Required Changes :1234: 
___
Hi @frankopkusianwar :wave: ,
Awesome job. You have almost covered all the changes asked by the previous reviewer. But there are a couple of issues that are still in here. Please check the comments below to resolve them.
___
### :spades: Mandatory Changes :spades: 
___
The list of methods is failing edge cases. Please fix them by following the instruction and don't forget to test them with the given samples.
- my_all?
- my_map
- my_inject
___
##### Please fix the issues mentioned above and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-04-23 19:26 UTC, shshamim63 commented on enumerable_custom.rb
> +  end
`my_all?` identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)) 
- when a class is passed as an argument returns true if all of the collection is a member of such class
```ruby
[1, 2, 3].my_all?(Integer) #should return true
[1, 2, nil].my_all?(Integer) #should return false
```
- when a Regex is passed as an argument returns true if all of the collection matches the Regex
```ruby
%w[dog door rod blade].my_all?(/d/)   #should return true.
%w[dog door rod blade].my_all?(/t/)   #should return false.
```

2020-04-23 19:26 UTC, shshamim63 commented on enumerable_custom.rb
> +  end
`my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- returns a new array with the results of running block once for every element in enum
```ruby
block = proc { |num| num < (1 + 10) / 2 }
[1, 2 ,3].my_map(&block)   #should return [1, 2, 3]
[6, 7 ,5].my_map { |num| num > 5 }   #should also return [6, 7]
```

2020-04-23 19:26 UTC, shshamim63 commented on enumerable_custom.rb
> +  end
`my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
- combines all elements of enum by applying a binary operation, specified by a block
```ruby
[1, 2, 3].my_inject { |memo, num| memo + num } #should return 6
[1, 2, 3].my_inject(1) { |memo, num| memo + num } #should return 7
```

2020-04-24 11:50 UTC, whiz25 requested changes
## Great Job :+1: 
You have made most of the suggested changes but we still need to fix one failing edge case.
- [x] my_inject combines all elements of enum by applying a binary operation, specified by a block
```ruby
array = Array.new(100){rand(0...9)}
operation = proc { |sum, n| sum + n } 
array.my_inject(&operation) == array.inject(&operation) # should return true
```

### Martin Afani

2020-04-24 12:25 UTC, frankopkusianwar commented
> ## Great Job 
> You have made most of the suggested changes but we still need to fix one failing edge case.
> 
> * [x]  my_inject combines all elements of enum by applying a binary operation, specified by a block
> 
> ```ruby
> array = Array.new(100){rand(0...9)}
> operation = proc { |sum, n| sum + n } 
> array.my_inject(&operation) == array.inject(&operation) # should return true
> ```
> 
> ### Martin Afani

The test case for the age case above is passing when true is returned as shown in the screenshot below

![test_case](https://user-images.githubusercontent.com/40593659/80212293-e1f1c000-863f-11ea-8edb-62d7262c2519.PNG)

2020-04-24 16:39 UTC, whiz25 approved these changes
## Approved :clap: 
Merge and proceed to the next project. Best of luck.

### Martin Afani

2020-04-25 10:59 UTC, merged